"""unlink campsite and review tables

Revision ID: 8abe38d132b6
Revises: caf0f887e0d0
Create Date: 2018-10-21 04:32:42.759097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abe38d132b6'
down_revision = 'caf0f887e0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('contract_id', sa.String(length=20), nullable=True))
    op.add_column('review', sa.Column('park_id', sa.String(length=20), nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'camp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('camp_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'review', 'campsite', ['camp_id'], ['id'])
    op.drop_column('review', 'park_id')
    op.drop_column('review', 'contract_id')
    # ### end Alembic commands ###
