"""add name for user

Revision ID: aa9d0296e36a
Revises: a7b905ce64d2
Create Date: 2018-10-21 10:32:36.026480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9d0296e36a'
down_revision = 'a7b905ce64d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=24), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
